### PR TITLE
Ported jribble tests from scalagwt-old branch.

### PR DESCRIPTION
**Pull request by gkossakowski**
Tests were written by @stephenh for old scalagwt
branch. All I did was to check them out and
slightly adapt to newer code. Also, I fixed
resource loading. Specifically:
- adapted AST building in tests to small
  changes in protobuf descriptor
- changed resource loading to rely on
  classpath-based resource loading by using
  Guava's Resources class
- dump asts to disk only if they do not match
  those defined for given test

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @lexspoon.

**Comment by gkossakowski** [comment]
I thought that checkstyle is ran as part of `ant test`. I was wrong. I'll fix all issue. Thanks!

**Comment by gkossakowski** [comment]
Ok, it's even more interesting. Checkstyle does not cover tests:
https://github.com/scalagwt/scalagwt-gwt/blob/scalagwt/dev/build.xml#L281

Also, here the comment says that `ant test` runs checkstyle:
https://github.com/scalagwt/scalagwt-gwt/blob/scalagwt/build.xml#L122

but if you follow ant logic it turns out that it doesn't run checkstyle.

Anyway, since tests are not covered by checkstyle, should we bother?

**Comment by lexspoon** [comment]
Yes. The purpose of good style is not just to pass the tests.

**Comment by gkossakowski** [comment]
I'll fix style issues and follow with new pull request.

**Pull request closed without merging**
